### ISSUE TITLE
purpose of this project please 

### ISSUE THREAD

**Issue by lduboeuf** [ubports/goget-ubuntu-touch#4]
hi,

Sorry if  i'm too impatient or missed something, what is the purpose of this project?

**Comment by mariogrip** [comment]
This is the old *installer* to install ubuntu touch from canonical, its not developed on anymore and its mostly here for legacy reasons.

**Comment by lduboeuf** [comment]
ok, i would mark it as deprecated then or just as an archive.
thanks
